### ISSUE TITLE
Why is used sync.Mutex?

### ISSUE THREAD

**Issue by njacob1001** [jaevor/go-nanoid#5]
Reading this function I noticed you use sync,Mutex to lock a variable, however you are not using any go routine, so my question is about the purpose of this?

https://github.com/jaevor/go-nanoid/blob/master/nanoid.go#L84C9-L84C19

**Comment by PhakornKiong** [comment]
@njacob1001 
Not author, but i think i got an idea why `mutex` is required.

https://github.com/jaevor/go-nanoid/blob/master/nanoid.go#L82C2-L82C28

`id` is pre-allocated (it is outside the returned generator func) and is shared between runs for performance, hence the need of mutex.

the same generator might be run in two concurrent goroutine and result in race condition since it shares the `var id`
